name: Parse Files on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  parse-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt  # Assuming you have a requirements.txt file for dependencies

      - name: Run parse.py on each changed file
        id: parse-files
        run: |
          for file in $(git diff --name-only origin/master...$GITHUB_HEAD_REF); do
            if [ -e "$file" ]; then  # Check if the file exists (not deleted)
              python parse.py --before "$file" --after "origin/master:$file"
            else  # If the file is deleted, pass only the "before" version
              python parse.py --before "$file"
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Apply changes after parsing"
