name: Parse Files on Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*' # Trigger on any file change

jobs:
  parse-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run parse.py on changed files
        id: parse-files
        run: |
          # Get the list of changed files in the pull request
          for file in $(git diff --name-only origin/master HEAD --diff-filter=M); do
            if [ -f "$file" ]; then
              if [ -e "$file" ]; then
                # Get the old version of the file
                git show  origin/master:"$file" > temp_before_file
                # Get the new version of the file
                git show HEAD:"$file" > temp_after_file
                # Run the parse script on both versions of the file
                python parse.py "temp_before_file" "temp_after_file"
                #rm temp_before_file temp_after_file
              else
                # Run the parse script on the deleted file (old version only)
                python parse.py "$file"
              fi
            fi
          done
      
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -am "Apply changes after parsing"
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to test
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
