name: Parse Files on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  parse-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch origin
        run: git fetch origin
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run parse.py on each changed file
        id: parse-files
        run: |
          git checkout $GITHUB_HEAD_REF -- $GITHUB_WORKSPACE
          for file in $(git diff --name-only origin/master...$GITHUB_HEAD_REF); do
            if [ -f "$file" ]; then
              if [ -e "$file" ]; then
                git show origin/master:"$file" > temp_after_file
                python parse.py "$file" "temp_after_file"
                rm temp_after_file
              else
                python parse.py "$file"
              fi
            fi
          done
      
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Apply changes after parsing"
